### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by acdcjunior** [adocs2/eslint-tslint-custom-rules#1]
a.js:
```js
function bob(stuff) {
        stuff.foo();
        console.log(("hello"), (stuff));
}

let x = (bob("x"));
```

command line:

```
~/# eslint --fix "a.js" --no-eslintrc --env "es6" --env "node" --parser-options "{ecmaVersion: 2018}" --rulesdir "/c3pr/rules" --rule "{no-console-custom: \"error\"}"
TypeError: Cannot read property 'name' of undefined
Occurred while linting /root/go/a.js:6
    at CallExpression (/c3pr/rules/no-console-custom.js:42:25)
    at listeners.(anonymous function).forEach.listener (/usr/local/lib/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/usr/local/lib/node_modules/eslint/lib/linter.js:752:32)
    at Array.forEach (<anonymous>)

```

**Comment by acdcjunior** [comment]
ressolveu? se sim, em qual commit? tu pode fechar ela direto no commit incluindo na msg dele algo tipo "fixes #1", aih o github automaticamente fecha a issue qdo voce dah o push.
